version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-desafio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bBK879@@
      MYSQL_DATABASE: desafio
    ports:
      - "3306:3306"
    networks:
      - desafio
  node:
    build: ./backend
    container_name: node-desafio
    restart: always
    environment:
      - VIRTUAL_HOST=api.batera.vickypr.es
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.batera.vickypr.es
      - LETSENCRYPT_EMAIL=admin@vickypr.es
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - desafio
      - proxy
    volumes:
      - ./backend:/usr/src/app
      - exclude:/usr/src/app/node_modules/
volumes:
  exclude:
networks:
  desafio:
  proxy:
    name: nginx-proxy
    external: true
